# GDSCRIPT
[language-server.godot]
command = "ncat"
args = ["127.0.0.1", "6005"]

[[language]]
name = "gdscript"
language-servers = ["godot"]
formatter = { command = "gdformat", args = ["-"] }
auto-format = true


# PYTHON
[language-server.pyrefly]
command = "pyrefly"
args = [ "lsp" ]

[[language]]
name = "python"
language-servers = [ "pyrefly" ]


# CMAKE
[language-server.cmake-language-server]
command = "cmake-language-server"

[[language]]
name = "cmake"
auto-format = true
language-servers = [ "cmake-language-server" ]
indent = { tab-width = 2, unit = "  " }


# C++
[language-server.clangd]
command = "clangd"
args = ["--compile-commands-dir=build"]

[[language]]
name = "cpp"
roots = ["CMakelists.txt"]
language-servers = ["clangd"]
file-types = ["c", "cpp", "h", "hpp"]
indent = { tab-width = 4, unit = "  " }


# SQL
[language-server.sql-language-server]
command = "sql-language-server"
args = ["up", "--method", "stdio"]

[[language]]
name = "sql"
scope = "source.sql"
language-servers = ["sql-language-server"]
file-types = ["sql"]


# Jinja
[language-server.jinja-lsp]
command = "jinja-lsp"
config = { templates = "./templates", backend = ["./src"], lang = "rust"}
timeout = 5

[[language]]
name = "jinja"
language-servers = ["jinja-lsp"]
